server:
  port: 80

spring:
  datasource:
    url: jdbc:sqlite:gateway-center/src/main/resources/tb-gateway-center.sqlite
    driver-class-name: org.sqlite.JDBC

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location:  classpath:/config/mybatis-config.xml